// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { context } from './helmetContext';
import { HelmetProvider } from '/Users/congxiaochen/Documents/umy/node_modules/.pnpm/@umijs+renderer-react@4.0.89_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
};
