// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp';
export type { RuntimeConfig } from './core/defineApp';
export { createHistory, history } from './core/history';
export { terminal } from './core/terminal';
// test
export { TestBrowser } from './testBrowser';
// plugins
export { getSketchJSON } from '/Users/congxiaochen/Documents/umy/.dumi/tmp/plugin-html2sketch';
// plugins types.d.ts
// @umijs/renderer-*
export {
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  createSearchParams,
  generatePath,
  Helmet,
  HelmetProvider,
  Link,
  matchPath,
  matchRoutes,
  Navigate,
  NavLink,
  Outlet,
  renderClient,
  resolvePath,
  useAppData,
  useClientLoaderData,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRouteData,
  useRouteProps,
  useRoutes,
  useSearchParams,
  useSelectedRoutes,
  useServerLoaderData,
  withRouter,
  __getRoot,
  __useFetcher,
} from '/Users/congxiaochen/Documents/umy/node_modules/.pnpm/@umijs+renderer-react@4.0.89_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type { History } from '/Users/congxiaochen/Documents/umy/node_modules/.pnpm/@umijs+renderer-react@4.0.89_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export {
  ApplyPluginsType,
  PluginManager,
} from '/Users/congxiaochen/Documents/umy/node_modules/.pnpm/umi@4.0.89_@babel+core@7.23.5_@types+node@17.0.45_@types+react@18.2.45_eslint@8.56.0_prettier_pvf3bpf35jrafjefi7ey5nhtam/node_modules/umi/client/client/plugin.js';
// react ssr
export const useServerInsertedHTML: Function = () => {};
