// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import {
  demos as dm8,
  frontmatter as fm8,
  texts as txt8,
  toc as toc8,
} from '/Users/congxiaochen/Documents/umy/docs/components/button.md?type=meta';
import {
  demos as dm4,
  frontmatter as fm4,
  texts as txt4,
  toc as toc4,
} from '/Users/congxiaochen/Documents/umy/docs/components/checkbox.md?type=meta';
import {
  demos as dm15,
  frontmatter as fm15,
  texts as txt15,
  toc as toc15,
} from '/Users/congxiaochen/Documents/umy/docs/components/chip.md?type=meta';
import {
  demos as dm9,
  frontmatter as fm9,
  texts as txt9,
  toc as toc9,
} from '/Users/congxiaochen/Documents/umy/docs/components/dialog.md?type=meta';
import {
  demos as dm6,
  frontmatter as fm6,
  texts as txt6,
  toc as toc6,
} from '/Users/congxiaochen/Documents/umy/docs/components/divider.md?type=meta';
import {
  demos as dm3,
  frontmatter as fm3,
  texts as txt3,
  toc as toc3,
} from '/Users/congxiaochen/Documents/umy/docs/components/elevation.md?type=meta';
import {
  demos as dm20,
  frontmatter as fm20,
  texts as txt20,
  toc as toc20,
} from '/Users/congxiaochen/Documents/umy/docs/components/fab.md?type=meta';
import {
  demos as dm1,
  frontmatter as fm1,
  texts as txt1,
  toc as toc1,
} from '/Users/congxiaochen/Documents/umy/docs/components/focus-ring.md?type=meta';
import {
  demos as dm0,
  frontmatter as fm0,
  texts as txt0,
  toc as toc0,
} from '/Users/congxiaochen/Documents/umy/docs/components/icon-button.md?type=meta';
import {
  demos as dm16,
  frontmatter as fm16,
  texts as txt16,
  toc as toc16,
} from '/Users/congxiaochen/Documents/umy/docs/components/icon.md?type=meta';
import {
  demos as dm17,
  frontmatter as fm17,
  texts as txt17,
  toc as toc17,
} from '/Users/congxiaochen/Documents/umy/docs/components/list.md?type=meta';
import {
  demos as dm18,
  frontmatter as fm18,
  texts as txt18,
  toc as toc18,
} from '/Users/congxiaochen/Documents/umy/docs/components/menu.md?type=meta';
import {
  demos as dm5,
  frontmatter as fm5,
  texts as txt5,
  toc as toc5,
} from '/Users/congxiaochen/Documents/umy/docs/components/progress.md?type=meta';
import {
  demos as dm14,
  frontmatter as fm14,
  texts as txt14,
  toc as toc14,
} from '/Users/congxiaochen/Documents/umy/docs/components/radio.md?type=meta';
import {
  demos as dm10,
  frontmatter as fm10,
  texts as txt10,
  toc as toc10,
} from '/Users/congxiaochen/Documents/umy/docs/components/ripple.md?type=meta';
import {
  demos as dm11,
  frontmatter as fm11,
  texts as txt11,
  toc as toc11,
} from '/Users/congxiaochen/Documents/umy/docs/components/select.md?type=meta';
import {
  demos as dm12,
  frontmatter as fm12,
  texts as txt12,
  toc as toc12,
} from '/Users/congxiaochen/Documents/umy/docs/components/slider.md?type=meta';
import {
  demos as dm13,
  frontmatter as fm13,
  texts as txt13,
  toc as toc13,
} from '/Users/congxiaochen/Documents/umy/docs/components/switch.md?type=meta';
import {
  demos as dm19,
  frontmatter as fm19,
  texts as txt19,
  toc as toc19,
} from '/Users/congxiaochen/Documents/umy/docs/components/tabs.md?type=meta';
import {
  demos as dm2,
  frontmatter as fm2,
  texts as txt2,
  toc as toc2,
} from '/Users/congxiaochen/Documents/umy/docs/components/text-field.md?type=meta';
import {
  demos as dm23,
  frontmatter as fm23,
  texts as txt23,
  toc as toc23,
} from '/Users/congxiaochen/Documents/umy/docs/quick-start.md?type=meta';
import {
  demos as dm26,
  frontmatter as fm26,
  texts as txt26,
  toc as toc26,
} from '/Users/congxiaochen/Documents/umy/docs/README.md?type=meta';
import {
  demos as dm24,
  frontmatter as fm24,
  texts as txt24,
  toc as toc24,
} from '/Users/congxiaochen/Documents/umy/docs/roadmap.md?type=meta';
import {
  demos as dm27,
  frontmatter as fm27,
  texts as txt27,
  toc as toc27,
} from '/Users/congxiaochen/Documents/umy/docs/size.md?type=meta';
import {
  demos as dm25,
  frontmatter as fm25,
  texts as txt25,
  toc as toc25,
} from '/Users/congxiaochen/Documents/umy/docs/support.md?type=meta';
import {
  demos as dm22,
  frontmatter as fm22,
  texts as txt22,
  toc as toc22,
} from '/Users/congxiaochen/Documents/umy/docs/theming/color.md?type=meta';
import {
  demos as dm21,
  frontmatter as fm21,
  texts as txt21,
  toc as toc21,
} from '/Users/congxiaochen/Documents/umy/docs/theming/README.md?type=meta';
import {
  demos as dm7,
  frontmatter as fm7,
  texts as txt7,
  toc as toc7,
} from '/Users/congxiaochen/Documents/umy/docs/theming/typography.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/components/icon-button': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/components/focus-ring': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/components/text-field': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/components/elevation': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/components/checkbox': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/components/progress': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/components/divider': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/theming/typography': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/components/button': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/components/dialog': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/components/ripple': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/components/select': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/components/slider': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/components/switch': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/components/radio': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/components/chip': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/components/icon': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/components/list': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/components/menu': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/components/tabs': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/components/fab': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/theming/README': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/theming/color': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/quick-start': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/roadmap': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/support': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/README': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/size': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
};

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
