// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/congxiaochen/Documents/umy/node_modules/.pnpm/dumi@2.2.16_@babel+core@7.23.5_@types+node@17.0.45_@types+react@18.2.45_eslint@8.56.0_prettie_a27ihx7dg6wuwhuauddydufcjy/node_modules/dumi/theme-default/builtins/Previewer/index.js';
